const LOADING = 'LOADING';
const GET_PROFILE = 'GET_PROFILE';
const ERROR = 'ERROR';
const OPTION_PICK = 'OPTION_PICK';
const DATA_CHART = 'DATA_CHART';
const STATUS_TIME_OPTIONS = 'STATUS_TIME_OPTIONS';
const DATA_CLASIFY = 'ATA_CLASIFY';

export { 
  LOADING, 
  GET_PROFILE, 
  ERROR,
  OPTION_PICK,
  DATA_CHART,
  STATUS_TIME_OPTIONS, 
  DATA_CLASIFY
 };
 